# Generated by Django 3.0.7 on 2020-06-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='messages',
        ),
    ]
