# Generated by Django 3.0.7 on 2020-06-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mark_read',
            field=models.BooleanField(default=False),
        ),
    ]
